# -*- coding: utf-8 -*-
"""Model_Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ayrqYPG2OfKVgwkpf1dBsiL3-RXfyAz

# **6DOF-ARM** 🛠

## **IMPORT LIBRARIES**
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import matplotlib.pyplot as plt

"""## **LOAD DATASET**"""

df = pd.read_csv('https://raw.githubusercontent.com/Prinak-Ghosh/6DOF-Arm/refs/heads/main/ML%20Model/Master%20Data%20Set.csv')
df

df = df.rename(columns={
    'Linear Displacement (mm)': 'lin_disp_mm',
    'Velocity (mm/sec)': 'lin_vel_mm_s',
    'Acceleration (mm/sec**2)': 'lin_acc_mm_s2',
    'Angular Displacement1 (deg)': 'ang_disp_deg',
    'Angular Velocity1 (deg/sec)': 'ang_vel_deg_s',
    'Angular Acceleration1 (deg/sec**2)': 'ang_acc_deg_s2',
    'Motor Torque - Z - (newton-mm)': 'torque_Nmm'
})
df

"""## **FEATURES & TARGET**"""

y = df['torque_Nmm']
y

x = df.drop('torque_Nmm',axis=1)
x

"""## **TRAIN / TEST SPLIT**"""

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

x_train

x_test

"""## **MODEL 1 — LINEAR REGRESSION**"""

lr_model = LinearRegression()
lr_model.fit(x_train, y_train)

y_pred_lr = lr_model.predict(x_test)

lr_mae = mean_absolute_error(y_test, y_pred_lr)
lr_rmse = np.sqrt(mean_squared_error(y_test, y_pred_lr))
lr_r2 = r2_score(y_test, y_pred_lr)

print("Linear Regression Results")
print("MAE:", lr_mae)
print("RMSE:", lr_rmse)
print("R²:", lr_r2)

"""## **Linear Regression Plot**"""

plt.figure()
plt.scatter(y_test, y_pred_lr, alpha=0.6)
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()])
plt.xlabel("Actual Torque (Nm)")
plt.ylabel("Predicted Torque (Nm)")
plt.title("Linear Regression: Actual vs Predicted Torque")
plt.show()

"""## **MODEL 2 — RANDOM FOREST REGRESSOR**"""

rf_model = RandomForestRegressor(
    n_estimators=200,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(x_train, y_train)   # no scaling needed

y_pred_rf = rf_model.predict(x_test)

rf_mae = mean_absolute_error(y_test, y_pred_rf)
rf_rmse = np.sqrt(mean_squared_error(y_test, y_pred_rf))
rf_r2 = r2_score(y_test, y_pred_rf)

print("\nRandom Forest Results")
print("MAE:", rf_mae)
print("RMSE:", rf_rmse)
print("R²:", rf_r2)

"""## **Random Forest Plot**"""

plt.figure()
plt.scatter(y_test, y_pred_rf, alpha=0.6)
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()])
plt.xlabel("Actual Torque (Nm)")
plt.ylabel("Predicted Torque (Nm)")
plt.title("Random Forest: Actual vs Predicted Torque")
plt.show()

"""## **MODEL 3 — GRADIENT BOOSTING REGRESSOR**"""

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

gbr = GradientBoostingRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gbr.fit(x_train, y_train)

y_pred_gbr = gbr.predict(x_test)

gbr_r2 = r2_score(y_test, y_pred_gbr)
gbr_rmse = np.sqrt(mean_squared_error(y_test, y_pred_gbr))

print("Gradient Boosting R²:", gbr_r2)
print("Gradient Boosting RMSE:", gbr_rmse)

"""## **GRADIENT BOOSTING REGRESSOR PLOT**"""

import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import r2_score, mean_squared_error

# Predictions already computed
y_pred_gbr = gbr.predict(x_test)

# Metrics (optional, for annotation)
r2 = r2_score(y_test, y_pred_gbr)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_gbr))

plt.figure(figsize=(8,6))

plt.scatter(y_test, y_pred_gbr, alpha=0.6)
plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    linestyle='--'
)

plt.xlabel("Actual Torque (N·m)")
plt.ylabel("Predicted Torque (N·m)")
plt.title("Gradient Boosting Regressor: Actual vs Predicted Torque")

# Optional text on plot
plt.text(
    0.05, 0.95,
    f"R² = {r2:.3f}\nRMSE = {rmse:.3f}",
    transform=plt.gca().transAxes,
    verticalalignment='top'
)

plt.grid(True)
plt.show()

"""## **COMPARISON TABLE (Linear vs RF vs GB)**"""

results = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest", "Gradient Boosting"],
    "R² Score": [
        r2_score(y_test, y_pred_lr),
        r2_score(y_test, y_pred_rf),
        gbr_r2
    ],
    "RMSE": [
        np.sqrt(mean_squared_error(y_test, y_pred_lr)),
        np.sqrt(mean_squared_error(y_test, y_pred_rf)),
        gbr_rmse
    ]
})

print(results)

"""## **ONE SUMMARY PLOT**"""

plt.figure(figsize=(8,6))

plt.scatter(y_test, y_pred_lr, alpha=0.5, label="Linear Regression")
plt.scatter(y_test, y_pred_rf, alpha=0.5, label="Random Forest")
plt.scatter(y_test, y_pred_gbr, alpha=0.5, label="Gradient Boosting")

plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()],
         linestyle='--',
         label="Ideal Prediction")

plt.xlabel("Actual Torque (N·m)")
plt.ylabel("Predicted Torque (N·m)")
plt.title("Actual vs Predicted Torque Comparison")
plt.legend()
plt.grid(True)
plt.show()